# -*- coding: utf-8 -*-
"""encapsulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VirDo0V_Nf3yuKuVlo1fZp6wGrYWY6jV

encapsulation
"""

class Example:
  def  __init__(self):
    self.public_var = "I'm public"
    self.__private_var = "I'm private"
  def show_private(self):
    print(self.__private_var)
obj = Example()
print(obj.public_var)
obj.show_private()

class kavya:
  def __init__(self):
    self.public_var = "I'm very talented"
    self.__private_var = "I'm good girl"
  def show_private(self):
    print(self.__private_var)
Affu = kavya()
print(Affu.public_var)
Affu.show_private()
