# -*- coding: utf-8 -*-
"""file handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H12rOYDYgTV1AnT_69cIdlfAkXuhQkKh
"""

file = open('kavya.txt', 'r')
content=file.read()
print(content)
file.close()

file = open('kavya.txt', 'w')
content=file.write("i am kavya jyothi k a")
print(content)
file.close()

file = open('kavya.txt', 'a')
content=file.write("i am kavya jyothi k a")
print(content)
file.close()
