# -*- coding: utf-8 -*-
"""for.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/168TMcpTlSgKcRe349MJgiHqejdaW0uIL

for(start,stop,step)
"""

for i in range(5,50,5):
  print("iteration:",i)

"""for(start,step)"""

for i in range(10,20):
  print("iteration:",i)

"""for(start)"""

for i in range(5):
  print("iteration:",i)
