# -*- coding: utf-8 -*-
"""functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X87AYvgi20qXkdGxfOH4CPXk_SY-zJOg
"""

def greet():
    print("Hello, Welcome to Python!")


greet()

"""variable length argument"""

def add_numbers(*args):
    print(sum(args))

add_numbers(1, 2, 3, 4)

"""keyword argument

default argument
"""

def greet(name="Guest"):
    print(f"Hello {name}!")

greet("Bob")
greet()

"""positional argument"""

def greet(name, age):
    print(f"Hello {name}, you are {age} years old!")

greet("Alice", 25)
greet(25, "Alice")

"""rajeev calls his number"""

def make_call(name, phone_number):
    print(f"{name} is calling his own number {phone_number}...")

make_call("Rajeev", "+919876543210")