# -*- coding: utf-8 -*-
"""inheritance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTSiWC22MHQ2kfovatGzPFuMRH7iXD79
"""

class bank_account:
  def __init__(self,account_number,balance=0):
    self.account_number=account_number
    self.balance=balance
  def deposit(self,amount):
    self.balance+=amount
    print(f"Deposited ${amount}. New balance is ${self.balance}")
  def withdraw(self,amount):
    if amount<=self.balance:
      self.balance-=amount
      print(f"Withdrew ${amount}. New balance is ${self.balance}")
    else:
      print("Insufficient funds")
  def check_balance(self):
    print(f"Account balance for account number {self.account_number}: ${self.balance}")

account = bank_account("123456789")
account.deposit(1000)
account.withdraw(500)
account.check_balance()
account.withdraw(1500)
account.check_balance()

class Animal:
  def speak(self):
    print("i'm an Animal")

class Dog(Animal):
  def speak(self):
    print("I bark")

d = Dog()   #object creation
d.speak()

class bird:
  def chirp(self):
    print ("i'm a bird")
class Duck(bird):
  def chirp(self):
    print("i quack")
d = Duck()
d.chirp()

class A:
  def feature1(self):
    print("Feature 1")
class B:
  def feature2(self):
    print("Feature 2")
class C(A,B):
    pass
obj=C()
obj.feature1()

class Afreen:
  def write(self):
    print("she can write")
class kavya:
  def read(self):
    print("she can read")
class sudha(Afreen,kavya):
  pass
nisha=sudha()
nisha.write()
nisha.read()

class Vehicle:
  def __init__(self,name,model):
    self.name=name
    self.model=model
  def info(self):
    print(f"Name: {self.name}\nModel: {self.model}")
class Car(Vehicle):
  def __init__(self,name,model,color):
    super().__init__(name,model)
    self.color=color
  def info(self):
    super().info()
    print(f"Color: {self.color}")
car=Car("rolls royce","2023","red")
car.info()