# -*- coding: utf-8 -*-
"""kavya.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11n7ZSlpkFWrNzb7xAvnken9oXp8NPMD0
"""

import mymodule

mymodule.kavya()

mymodule.age()
