# -*- coding: utf-8 -*-
"""mymodule.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C4D5tCbyyBTzz9aducsgflFFQJodY6ih
"""

def kavya():
  print("Kavya Jyothi")
def age():
  print("19")
