# -*- coding: utf-8 -*-
"""oops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/182xxomF-cV6sdK_lxThfjxmbjLIKZ6F5
"""

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age
  def greet(self):
    print(f"Hello, my name is {self.name} and I am {self.age} years old.")

p1 = Person("Alice", 25)
p1.greet()
