# -*- coding: utf-8 -*-
"""oops1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/182xxomF-cV6sdK_lxThfjxmbjLIKZ6F5

with consructor
"""

class kavya:
  def __init__(self, name, age):
    self.name = name
    self.age = age
  def cat(self):
    print(f"Hello, my name is {self.name} and I am {self.age} years old.")
    print("i love cats and dog ")

kavya1 = kavya("Affu", 20)
kavya1.cat()

"""without constructor"""

class kavya:
  def cat(self):
    print("i love cats and dog ")

kavya1 = kavya()
kavya1.cat()

class circle:
  def __init__(self, radius):
    self.radius = radius
  def area(self):
    return 3.14 * self.radius ** 2
  def display(self):
    print(f"Circle with radius {self.radius}:")
    print(f"Area: {self.area():.2f}")
circle1 = circle(radius=5)
circle1.display()



class circle:
  def area(self):
    return 3.14 * self.radius ** 2
circle1 = circle()
circle1.radius = 5
print(circle1.area())
